PREFIX : <http://www.purl.org/mentalhealth#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
SELECT ?option ?subclass 
WHERE {
    { SELECT ?label ?pl ?subclass
      WHERE {
        ?subclass rdfs:subClassOf* ?intermediate .
        ?intermediate rdfs:subClassOf* :MentalDisorder .
        ?subclass rdfs:label ?label .
        OPTIONAL { ?label skos:prefLabel ?pl }
      }
    GROUP BY ?label ?subclass
    HAVING(count(?intermediate) = 2)
    }
    BIND ( IF ( !bound(?label), ?subclass, IF ( bound(?label), IF ( !bound(?pl), ?label, ?pl), '' ) ) AS ?option )
}
GROUP BY ?subclass
ORDER BY ?option