PREFIX : <http://www.purl.org/mentalhealth#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?option ?subclass 
WHERE {
  ?subclass rdfs:subClassOf* ?intermediate .
  ?intermediate rdfs:subClassOf* :MentalDisorder .
  ?subclass rdfs:label ?label .
  BIND ( IF ( !bound(?label), ?subclass, IF ( bound(?label), ?label, '' ) ) AS ?option )
}
GROUP BY ?option ?subclass
HAVING(count(?intermediate) = 2)
ORDER BY ?option