#!/usr/bin/env python
"""
This program converts four specific mental health spreadsheet workbooks to RDF
text documents.

Authors:
    - Arno Klein, 2017  (arno@childmind.org)  http://binarybottle.com
    - Jon Clucas, 2017 – 2018 (jon.clucas@childmind.org)

Copyright 2018, Child Mind Institute MATTER Lab (https://matter.childmind.org),
Apache v2.0 License

"""
import os
import sys
mhdb_path = os.path.abspath(
    os.path.join(
        __file__,
        os.pardir,
        os.pardir,
        os.pardir
    )
)
if mhdb_path not in sys.path:
    sys.path= [
        mhdb_path,
        *sys.path
    ]
try:
    from mhdb.info import __version__ as version
    from mhdb.ingest import *
    from mhdb.spreadsheet_io import download_google_sheet
    from mhdb.write_ttl import check_iri, turtle_from_dict, write_header
except:
    from mhdb.mhdb.info import __version__ as version
    from mhdb.mhdb.ingest import *
    from mhdb.mhdb.spreadsheet_io import download_google_sheet
    from mhdb.mhdb.write_ttl import check_iri, turtle_from_dict, write_header
import numpy as np
import pandas as pd


def main():
    # ------------------------------------------------------------------------------
    # Try to get latest spreadsheets
    # Except use local copies
    # ------------------------------------------------------------------------------
    try:
        behaviorFILE = download_google_sheet(
            'data/separating.xlsx',
            "1sQp63K5nGrYSgK2ZvsTfTDmlM4W5_eFHfy6Ckoi7yP4"
        )
    except:
        behaviorFILE = 'data/separating.xlsx'
    try:
        mentalhealthFILE = download_google_sheet(
            'data/mentalhealth.xlsx',
            "1MfW9yDw7e8MLlWWSBBXQAC2Q4SDiFiMMb7mRtr7y97Q"
        )
    except:
        mentalhealthFILE = 'data/mentalhealth.xlsx'
    try:
        technologyFILE = download_google_sheet(
            'data/technology.xlsx',
            "1cuJXT1Un7HPLYcDyHAXprH-wGS1azuUNmVQnb3dV1cY"
        )
    except:
        technologyFILE = 'data/technology.xlsx'
    base_uri = "http://www.purl.org/mentalhealth"
    outfile = os.path.join(os.getcwd(), 'behavior.ttl')
    dsm_outfile = os.path.join(os.getcwd(), 'dsm.ttl')

    # ------------------------------------------------------------------------------
    # Import spreadsheets
    # ------------------------------------------------------------------------------
    behavior_xls = pd.ExcelFile(behaviorFILE)
    mentalhealth_xls = pd.ExcelFile(mentalhealthFILE)
    technology_xls = pd.ExcelFile(technologyFILE)
    X = ['', 'nan', np.nan, 'None', None]

    # ------------------------------------------------------------------------------
    # Create output RDF mentalhealthFILE
    # ------------------------------------------------------------------------------
    label = "mental health database"
    comment="""
    ======================
    Mental Health Database
    ======================

    This mental health database inter-relates information about mental health
    diagnoses, symptoms, assessement questionnaires, etc., and is licensed
    under the terms of the Creative Commons BY license.
    Current information can be found on the website, http://mentalhealth.tech.
    """

    statements = technology(
        technology_xls,
        mentalhealth_xls,
        BehaviorSheet1(
            behavior_xls = behavior_xls,
            mentalhealth_xls = mentalhealth_xls
        )
    )

    dsm_statements = {
        statement: statements[
            statement
        ] for statement in statements if (
            (
                "dcterms:source" in statements[statement]
            ) and any(
                "dsm" in s for s in [
                    source.lower() for source in statements[
                        statement
                    ][
                        "dcterms:source"
                    ]
                ]
            )
        )
    }

    non_dsm_statements = {
        statement: statements[
            statement
        ] for statement in statements if statement not in dsm_statements
    }

    mhdb_turtle = turtle_from_dict(non_dsm_statements)
    dsm_turtle = turtle_from_dict(dsm_statements)

    import_prefixes = set()
    for subject in statements:
        if ":" in subject and \
        "://" not in subject and \
        not subject.startswith('"'):
            import_prefixes.add(subject.split(":")[0])
        for predicate in statements[subject]:
            if ":" in predicate and \
            "://" not in predicate and \
            not predicate.startswith('"'):
                import_prefixes.add(predicate.split(":")[0])
            for object in statements[subject][predicate]:
                if ":" in object and \
                "://" not in object and \
                not object.startswith('"'):
                    import_prefixes.add(object.split(":")[0])

    # ------------------------------------------------------------------------------
    # Extract worksheets as pandas dataframes
    # ------------------------------------------------------------------------------
    prefixes = [(
        row[1]["Prefix"],
        row[1]["PrefixURI"],
        row[1]["ImportURI"]
    ) for row in mentalhealth_xls.parse(
        'Ontologies'
    ).iterrows() if row[1]["Prefix"] in import_prefixes]
    # ------------------------------------------------------------------------------
    # Write header
    # with Ontologies listed in mentalhealth.Ontologies ------------------------------------------------------------------------------

    fid = open(outfile, 'w')
    dsmfid = open(dsm_outfile, 'w')
    header_string = write_header(
        base_uri,
        version,
        label,
        comment,
        prefixes=prefixes,
        imports=True
    )
    fid.write(header_string)
    dsmfid.write(write_header(
        "{0}/{1}".format(base_uri, "dsm"),
        version,
        "{0} — {1}".format(label, "DSM-V supplement"),
        "\n".join([
            comment,
            "\t\t================\n\t\tDSM-V supplement\n\t\t================"
        ]),
        prefixes=prefixes
    ))

    fid.write("{0} .\n".format(mhdb_turtle.rstrip(" .")))
    dsmfid.write("{0} .\n".format(dsm_turtle.rstrip(" .")))

if __name__ == "__main__":
    main()
